export const SET_AVAILABLE_FILTER = 'SET_AVAILABLE_FILTER';
export const SET_KILOMETERS_RANGE_FILTER = 'SET_KILOMETERS_RANGE_FILTER';
export const FETCH_VEHICLES = 'FETCH_VEHICLES';
export const FETCH_VEHICLES_FAILED = 'FETCH_VEHICLES_FAILED';